### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by abhay-vaidya** [abhay-vaidya/personal-website#1]
## Todo

- [x] Add Projects section
- [x] Use square AIR MILES logo
- [x] Use higher res profile image
- [x] Add favicon
- [x] Use better gradient image (?)
- [x] Extract data out of components
- [x] Add footer
- [x] Finalize copy
- [x] Optimize images
- [x] Add "scroll down" arrow above fold
- [x] Get rid of class components and use hooks for state/side effects

## Nice to have

- [x] [Viewport enter animations](https://www.react-reveal.com/)
- [ ] Light/Dark mode toggle

## Next steps

- [x] Upgrade to Tailwindcss 1.0 when officially released (or before!)
- [ ] Build API to serve data so site doesn't have to be redeployed every time
